
[armbian-pine64-star64]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "armbian/community"

[buildroot-sdk-milkv-duo-python]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-duo/duo-buildroot-sdk"

[buildroot-sdk-milkv-duo]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-duo/duo-buildroot-sdk"

[buildroot-sdk-milkv-duo256m-python]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-duo/duo-buildroot-sdk"

[buildroot-sdk-milkv-duo256m]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-duo/duo-buildroot-sdk"

[buildroot-sdk-milkv-duos-sd]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-duo/duo-buildroot-sdk"

[buildroot-sdk-sipeed-licheervnano]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "sipeed/LicheeRV-Nano-Build"

[debian-desktop-sdk-milkv-mars-cm-sd]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-mars/mars-buildroot-sdk"

[debian-desktop-sdk-milkv-mars-sd]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "milkv-mars/mars-buildroot-sdk"

[debian-fishwaldo-sg200x-sipeed-licheervnano]
type = "GITHUB_SINGLE"
issueto = "weilinfox/ruyi-reimu"
repo = "Fishwaldo/sophgo-sg200x-debian"

[revyos-milkv-meles]
type = "GITHUB_MULTI"

[revyos-sg2042-milkv-pioneer]
type = "MIRROR_SINGLE"
host = "mirror.iscas.ac.cn"
path = "/revyos/extra/images/sg2042"
match = "^[0-9]+$"
issueto = "weilinfox/ruyi-reimu"

[revyos-sipeed-lc4a]
type = "MIRROR_MULTI"

[revyos-sipeed-lcon4a]
type = "GITHUB_MULTI"

[revyos-sipeed-lpi4a]
type = "GITHUB_MULTI"
